import type { Product } from "@/types/game";

// ── 50 Mock Product SKUs ──────────────────────────────────────────────────────
// All prices in VND (integer). Covers Electronics, Home, Beauty, Food, Fashion.

export const MOCK_PRODUCTS: Product[] = [
  // Electronics
  {
    productId: "p001",
    name: "Robot Hút Bụi Xiaomi G1",
    image: "/assets/products/p001.webp",
    price: 2490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Xiaomi",
    affiliateLink: "https://shopee.vn/product/p001",
  },
  {
    productId: "p002",
    name: "Tai Nghe Bluetooth Sony WF-1000XM5",
    image: "/assets/products/p002.webp",
    price: 5990000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Sony",
    affiliateLink: "https://shopee.vn/product/p002",
  },
  {
    productId: "p003",
    name: "Loa Bluetooth JBL Charge 5",
    image: "/assets/products/p003.webp",
    price: 3290000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "JBL",
    affiliateLink: "https://shopee.vn/product/p003",
  },
  {
    productId: "p004",
    name: "Bàn Phím Cơ Keychron K2",
    image: "/assets/products/p004.webp",
    price: 1890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Keychron",
    affiliateLink: "https://shopee.vn/product/p004",
  },
  {
    productId: "p005",
    name: "Chuột Không Dây Logitech MX Master 3",
    image: "/assets/products/p005.webp",
    price: 2190000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Logitech",
    affiliateLink: "https://shopee.vn/product/p005",
  },
  {
    productId: "p006",
    name: "Máy Lọc Không Khí Xiaomi 4 Pro",
    image: "/assets/products/p006.webp",
    price: 4290000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Xiaomi",
    affiliateLink: "https://shopee.vn/product/p006",
  },
  {
    productId: "p007",
    name: "Webcam Logitech C920s HD Pro",
    image: "/assets/products/p007.webp",
    price: 1490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Logitech",
    affiliateLink: "https://shopee.vn/product/p007",
  },
  {
    productId: "p008",
    name: "Màn Hình Gaming ASUS ROG 27 inch",
    image: "/assets/products/p008.webp",
    price: 8990000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "ASUS",
    affiliateLink: "https://shopee.vn/product/p008",
  },
  {
    productId: "p009",
    name: "Đồng Hồ Thông Minh Samsung Galaxy Watch 6",
    image: "/assets/products/p009.webp",
    price: 6490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Samsung",
    affiliateLink: "https://shopee.vn/product/p009",
  },
  {
    productId: "p010",
    name: "Sạc Dự Phòng Anker 20000mAh",
    image: "/assets/products/p010.webp",
    price: 890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Điện tử",
    brand: "Anker",
    affiliateLink: "https://shopee.vn/product/p010",
  },
  // Home & Kitchen
  {
    productId: "p011",
    name: "Nồi Cơm Điện Tử Panasonic 1.8L",
    image: "/assets/products/p011.webp",
    price: 1290000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Panasonic",
    affiliateLink: "https://shopee.vn/product/p011",
  },
  {
    productId: "p012",
    name: "Máy Xay Sinh Tố Philips HR2041",
    image: "/assets/products/p012.webp",
    price: 750000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Philips",
    affiliateLink: "https://shopee.vn/product/p012",
  },
  {
    productId: "p013",
    name: "Bình Giữ Nhiệt Stanley 1L",
    image: "/assets/products/p013.webp",
    price: 890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Stanley",
    affiliateLink: "https://shopee.vn/product/p013",
  },
  {
    productId: "p014",
    name: "Nồi Chiên Không Dầu Cosori 5.5L",
    image: "/assets/products/p014.webp",
    price: 1990000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Cosori",
    affiliateLink: "https://shopee.vn/product/p014",
  },
  {
    productId: "p015",
    name: "Máy Pha Cà Phê Delonghi Dedica",
    image: "/assets/products/p015.webp",
    price: 5490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Delonghi",
    affiliateLink: "https://shopee.vn/product/p015",
  },
  {
    productId: "p016",
    name: "Nước Giặt Downy 3kg",
    image: "/assets/products/p016.webp",
    price: 189000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Downy",
    affiliateLink: "https://shopee.vn/product/p016",
  },
  {
    productId: "p017",
    name: "Chảo Chống Dính Tefal 28cm",
    image: "/assets/products/p017.webp",
    price: 590000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Tefal",
    affiliateLink: "https://shopee.vn/product/p017",
  },
  {
    productId: "p018",
    name: "Bộ Dao Nhà Bếp Zwilling 5 Món",
    image: "/assets/products/p018.webp",
    price: 2790000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Zwilling",
    affiliateLink: "https://shopee.vn/product/p018",
  },
  {
    productId: "p019",
    name: "Quạt Điều Hoà Xiaomi ZLBPLDS03ZM",
    image: "/assets/products/p019.webp",
    price: 3490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Xiaomi",
    affiliateLink: "https://shopee.vn/product/p019",
  },
  {
    productId: "p020",
    name: "Bộ Ga Giường Cotton 100% King",
    image: "/assets/products/p020.webp",
    price: 690000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Gia dụng",
    brand: "Everon",
    affiliateLink: "https://shopee.vn/product/p020",
  },
  // Beauty & Personal Care
  {
    productId: "p021",
    name: "Serum Vitamin C Skinceuticals CE Ferulic",
    image: "/assets/products/p021.webp",
    price: 3890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Skinceuticals",
    affiliateLink: "https://shopee.vn/product/p021",
  },
  {
    productId: "p022",
    name: "Kem Chống Nắng Anessa SPF 50+ 60ml",
    image: "/assets/products/p022.webp",
    price: 490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Anessa",
    affiliateLink: "https://shopee.vn/product/p022",
  },
  {
    productId: "p023",
    name: "Son Môi MAC Ruby Woo",
    image: "/assets/products/p023.webp",
    price: 650000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "MAC",
    affiliateLink: "https://shopee.vn/product/p023",
  },
  {
    productId: "p024",
    name: "Dầu Gội Kérastase Resistance 250ml",
    image: "/assets/products/p024.webp",
    price: 890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Kérastase",
    affiliateLink: "https://shopee.vn/product/p024",
  },
  {
    productId: "p025",
    name: "Nước Hoa Chanel Coco Mademoiselle 50ml",
    image: "/assets/products/p025.webp",
    price: 4290000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Chanel",
    affiliateLink: "https://shopee.vn/product/p025",
  },
  {
    productId: "p026",
    name: "Máy Rửa Mặt Foreo Luna Mini 3",
    image: "/assets/products/p026.webp",
    price: 2290000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Foreo",
    affiliateLink: "https://shopee.vn/product/p026",
  },
  {
    productId: "p027",
    name: "Toner Paula's Choice BHA 2% 118ml",
    image: "/assets/products/p027.webp",
    price: 750000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Paula's Choice",
    affiliateLink: "https://shopee.vn/product/p027",
  },
  {
    productId: "p028",
    name: "Sữa Dưỡng Thể CeraVe 473ml",
    image: "/assets/products/p028.webp",
    price: 390000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "CeraVe",
    affiliateLink: "https://shopee.vn/product/p028",
  },
  {
    productId: "p029",
    name: "Máy Sấy Tóc Dyson Supersonic",
    image: "/assets/products/p029.webp",
    price: 12900000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Dyson",
    affiliateLink: "https://shopee.vn/product/p029",
  },
  {
    productId: "p030",
    name: "Mascara Benefit They're Real",
    image: "/assets/products/p030.webp",
    price: 590000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Làm đẹp",
    brand: "Benefit",
    affiliateLink: "https://shopee.vn/product/p030",
  },
  // Fashion
  {
    productId: "p031",
    name: "Giày Chạy Bộ Nike Air Zoom Pegasus 40",
    image: "/assets/products/p031.webp",
    price: 2890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Nike",
    affiliateLink: "https://shopee.vn/product/p031",
  },
  {
    productId: "p032",
    name: "Balo Laptop Samsonite Openroad 15.6\"",
    image: "/assets/products/p032.webp",
    price: 1690000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Samsonite",
    affiliateLink: "https://shopee.vn/product/p032",
  },
  {
    productId: "p033",
    name: "Áo Thun Uniqlo Airism Nam",
    image: "/assets/products/p033.webp",
    price: 249000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Uniqlo",
    affiliateLink: "https://shopee.vn/product/p033",
  },
  {
    productId: "p034",
    name: "Kính Mát Rayban Aviator Classic",
    image: "/assets/products/p034.webp",
    price: 3190000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Rayban",
    affiliateLink: "https://shopee.vn/product/p034",
  },
  {
    productId: "p035",
    name: "Túi Xách Tote Coach Signature Medium",
    image: "/assets/products/p035.webp",
    price: 6990000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Coach",
    affiliateLink: "https://shopee.vn/product/p035",
  },
  {
    productId: "p036",
    name: "Đồng Hồ Casio G-Shock GA-2100",
    image: "/assets/products/p036.webp",
    price: 2490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Casio",
    affiliateLink: "https://shopee.vn/product/p036",
  },
  {
    productId: "p037",
    name: "Giày Thể Thao Adidas Ultraboost 22",
    image: "/assets/products/p037.webp",
    price: 3690000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Adidas",
    affiliateLink: "https://shopee.vn/product/p037",
  },
  {
    productId: "p038",
    name: "Ví Da Nam Fossil Derrick Bifold",
    image: "/assets/products/p038.webp",
    price: 890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Fossil",
    affiliateLink: "https://shopee.vn/product/p038",
  },
  {
    productId: "p039",
    name: "Áo Khoác Bomber Zara Man",
    image: "/assets/products/p039.webp",
    price: 1290000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "Zara",
    affiliateLink: "https://shopee.vn/product/p039",
  },
  {
    productId: "p040",
    name: "Mũ Snapback New Era 59Fifty",
    image: "/assets/products/p040.webp",
    price: 790000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thời trang",
    brand: "New Era",
    affiliateLink: "https://shopee.vn/product/p040",
  },
  // Food & Nutrition
  {
    productId: "p041",
    name: "Whey Protein Optimum Nutrition Gold 2.27kg",
    image: "/assets/products/p041.webp",
    price: 1890000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thực phẩm",
    brand: "Optimum Nutrition",
    affiliateLink: "https://shopee.vn/product/p041",
  },
  {
    productId: "p042",
    name: "Trà Sữa Tiger Sugar Hộp 6 Lon",
    image: "/assets/products/p042.webp",
    price: 149000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thực phẩm",
    brand: "Tiger Sugar",
    affiliateLink: "https://shopee.vn/product/p042",
  },
  {
    productId: "p043",
    name: "Cà Phê Rang Xay Trung Nguyên 500g",
    image: "/assets/products/p043.webp",
    price: 290000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thực phẩm",
    brand: "Trung Nguyên",
    affiliateLink: "https://shopee.vn/product/p043",
  },
  {
    productId: "p044",
    name: "Socola Lindt Assorted 337g",
    image: "/assets/products/p044.webp",
    price: 390000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thực phẩm",
    brand: "Lindt",
    affiliateLink: "https://shopee.vn/product/p044",
  },
  {
    productId: "p045",
    name: "Mật Ong Nguyên Chất New Zealand 500g",
    image: "/assets/products/p045.webp",
    price: 690000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thực phẩm",
    brand: "Capilano",
    affiliateLink: "https://shopee.vn/product/p045",
  },
  // Health & Sports
  {
    productId: "p046",
    name: "Thảm Yoga TPE Cao Cấp 6mm",
    image: "/assets/products/p046.webp",
    price: 490000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thể thao",
    brand: "Gaiam",
    affiliateLink: "https://shopee.vn/product/p046",
  },
  {
    productId: "p047",
    name: "Dây Nhảy Crossrope Get Lean",
    image: "/assets/products/p047.webp",
    price: 990000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thể thao",
    brand: "Crossrope",
    affiliateLink: "https://shopee.vn/product/p047",
  },
  {
    productId: "p048",
    name: "Tạ Tay Điều Chỉnh Bowflex 24kg",
    image: "/assets/products/p048.webp",
    price: 4990000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thể thao",
    brand: "Bowflex",
    affiliateLink: "https://shopee.vn/product/p048",
  },
  {
    productId: "p049",
    name: "Máy Đo Huyết Áp Omron HEM-7120",
    image: "/assets/products/p049.webp",
    price: 790000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Sức khỏe",
    brand: "Omron",
    affiliateLink: "https://shopee.vn/product/p049",
  },
  {
    productId: "p050",
    name: "Bình Nước Thể Thao Hydro Flask 32oz",
    image: "/assets/products/p050.webp",
    price: 1190000,
    currency: "VND",
    source: "mock",
    updatedAt: "2026-09-11T00:00:00Z",
    category: "Thể thao",
    brand: "Hydro Flask",
    affiliateLink: "https://shopee.vn/product/p050",
  },
];

export function getProductById(productId: string): Product | undefined {
  return MOCK_PRODUCTS.find((p) => p.productId === productId);
}

export function getProductsByIds(productIds: string[]): Product[] {
  return productIds.map((id) => MOCK_PRODUCTS.find((p) => p.productId === id)).filter((p): p is Product => p !== undefined);
}
